#footprint: [[-0.14, -0.17], [-0.14, 0.17], [0.01, 0.17], [0.01,0.21], [0.14,0.21], [0.14, -0.21], [0.01,-0.21], [0.01,-0.17]] still under testing gives problem with update
footprint: [[-0.14, -0.20], [-0.14, 0.20], [0.14,0.20],[0.14, -0.20]]
footprint_padding: 0.02

robot_base_frame: marrtino_base_footprint

publish_frequency: 1
transform_tolerance: 0.5

resolution: 0.01

obstacle_range: 2.5
raytrace_range: 3.0

#map_type: costmap

static_layer:
  map_topic: map
  subscribe_to_updates: true
  enabled: true

obstacle_layer:
  observation_sources:  laser
  track_unknown_space: true
  combination_method: 1
  laser:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    min_obstacle_height: 0.1
    max_obstacle_height: 0.4

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  cost_scaling_factor:  2.58  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.75  # max distance from an obstacle at which costs are incurred for planning paths

