global_frame: map

rolling_window: false
track_unknown_space: false #was true
static_map: true #try false
update_frequency: 0.5

plugins:
  - {name: static_layer,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,                type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,               type: "costmap_2d::InflationLayer"}
