global_frame: marrtino_map
rolling_window: true
static_map: false
planner_frequency: 8.0
planner_patiente: 2.0
update_frequency: 10.0

inflation_layer:
  cost_scaling_factor:  0.1  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.08  # max distance from an obstacle at which costs are incurred for planning paths


plugins:
  - {name: obstacle_layer,                  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,                 type: "costmap_2d::InflationLayer"}
