controller_frequency: 5.0
planner_frequency: 1
oscillation_timeout: 5.0 #just added
max_planning_retries: 10
planner_patience: 2.0
controller_patience: 2.0
recovery_behaviour_enabled: true
clearing_rotation_allowed: false

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.00 # A tolerance on the goal point for the planner.


DWAPlannerROS:
  # Robot configuration parameters
  acc_lim_x: 1.5
  acc_lim_y: 0.0
  acc_lim_th: 2.0

  max_vel_x: 3.0
  min_vel_x: 0.1
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_rot_vel: 2
  min_rot_vel: 0.05

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false


  # # Forward Simulation Parameters
  sim_time: 3.0
 # sim_granularity: 0.01
  angular_sim_granularity: 0.01
  vx_samples: 20
  vy_samples: 1
  vth_samples: 40

  # # Trajectory scoring parameters
  path_distance_bias: 40.0 # The weighting for how much the controller should stay close to the path it was given
  goal_distance_bias: 25.0 # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  occdist_scale: 1.0 # The weighting for how much the controller should attempt to avoid obstacles
  forward_point_distance: 0.015 # The distance from the center point of the robot to place an additional scoring point, in meters
  stop_time_buffer: 0.02  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint, in m/sop before a collision in order for a trajectory to be considered valid in seconds
  scaling_speed: 5 # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  max_scaling_factor: 2 # The maximum factor to scale the robot's footprint by

  # # Oscillation Prevention Parameters
 # oscillation_reset_dist: 0.1 #0.05 just added
  #oscillation_reset_angle: 0.1 #just added